### ISSUE TITLE
No devices created

### ISSUE THREAD

**Issue by rezzalex** [CreasolTech/domoticz-hyundai-kia#6]
Hello.

I am using almost the latest DZ beta version with Docker.
I have instantiated the plugin using python plugin manager, enter my credentials for blue link, activated it and ... Nothing : no devices created, almost no logs (but I maybe need to raise my log level).

**Comment by CreasolTech** [comment]
Hi, 
you should see some lines in the Domoticz log when the plugin start.
Also, you have to wait for the polling time before the system start polling the cloud and vehicle to get info and create the devices.
Please keep me informed.

**Comment by rezzalex** [comment]
HI. I just followed the installation guide and same result.
To be noted: when modifying the plugin, the DZ web pages are then not answering....  I have then to restart the DZ container...
